# Drops existing tables, recreates them and executes import.sql
spring:
    jpa:
        hibernate:
            ddl-auto: update        show-sql: true
        hibernate:format_sql: true
 

# Settings for the oracle connection
    datasource:
        url:
            jdbc:oracle:thin:@localhost:1521:orcl
        username:
            system
        password:
            manager
        driver-class-oracle:
            jdbc:
                driver:
                    OracleDriver